### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-starter-react4xp#2]
In order to use the react4xp starter do I really need to read about chunks and other advanced concepts?

I feel like a starter should be as simple as possible. It's cool with all the advanced functionality, but perhaps everything complex should be moved to an advanced section in the documentation.

I just want to get up and running and coding as quick as possible.

**Comment by ComLock** [comment]
```Simply put, there are 4 prototypical usage patterns.```

I have never seen the word ```prototypical``` before. It doesn't feel ```simply``` to me.

**Comment by ComLock** [comment]
```Shorthand function```

What ever does that mean?

**Comment by espen42** [comment]
True. I've been thinking of moving the examples up first and moving the details later. Are the examples clear in themselves?

I think that a couple of things need to be clarified before the examples for them to make sense, though:
- the connection between where a source file is put and how it's referred in the code.
- that means the jsxPath concept needs to be clear,
- which again means the concepts of entries - and next, chunks.

I'll rewrite some, including the "prototypical" thing. :)

But I thought "shorthand" was pretty regular in programming? Sometimes you need the details, sometimes it's good to have a quick and easy and tight shortcut syntax...

https://www.google.com/search?ei=6z9EXd2TMNGsrgTt3qmgAg&q=shorthand+in+programming&oq=shorthand+in+pr&gs_l=psy-ab.3.0.0i22i30l10.7544.9007..10581...1.0..0.61.386.7......0....1..gws-wiz.......0i71j0i67j0.cj35b3ZbFLI
