### ISSUE TITLE
Make target id in example 2 a constant passed to thymeleaf

### ISSUE THREAD

**Issue by ComLock** [enonic/doc-starter-react4xp#5]
It should be possible to make the target id a constant in javascript and pass that to thymeleaf render. I think that is nicer than "hardcoding" it two places.

**Comment by espen42** [comment]
Nicer and better XP practice, but not clearer here. I think tutorials should never add complexity or stuff going on if it's not needed and doesn't show any part of what you're trying to teach. 

(I may have broken that promise somewhere else, but I feel like keeping this one as-is)
